<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/b9c1830c77.js" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="css/all.min.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
<div class="text-center" style="margin-bottom:170px;margin-top:100px">
<form class="form-signin" method="post">
  <img class="mb-4" src="/docs/4.6/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  <label for="inputEmail" class="sr-only ">Email address</label>
  <input type="email" 
    name="inputEmail"
    class="form-control<?php if(!empty($error['inputEmail'])) : ?> is-invalid <?php endif  ; ?> " placeholder="Email address"  
    required autofocus>
    <?php if(!empty($error['inputEmail'])) : ?>
      <div class="invalid-feedback text-danger"><?= $error['inputEmail'] ; ?></div>
    <?php endif  ; ?>
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password"
    name="inputPassword" 
    class="form-control<?php if(!empty($error['inputPassword'])) : ?> is-invalid <?php endif  ; ?> " 
    placeholder="Password" 
    required>
    <?php if(!empty($error['inputPassword'])) : ?>
      <div class="invalid-feedback text-danger"><?= $error['inputPassword'] ; ?></div>
    <?php endif  ; ?>
  <div class="checkbox my-2">
      <input type="checkbox" value="remember-me"> Remember me
  </div>
  <button class="btn btn-lg btn-primary btn-block w-50" type="submit" style="margin-left:70px;">Sign in</button>
  
    </form>
</div>
</body>
</html>