<div class="table-responsive mx-2">
    <?php if( $countcategory > 0 ) : ?>
          <small class="float-right m-5 text-primary">(<?= $countcategory; ?>) Categories</small>
          <small class="float-right m-5 text-primary">(<?= $countcategory; ?>) vu</small>
    <?php endif; ?>
   <div class="mt-4">
   <a
    class="btn btn-warning"
    title="add une categorie"
    href="admin_category_insert.php">
    Add 
   </a>
   </div>
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Categories</th>
              <th scope="col" class="text-center" colspan="2">Action</th>
            </tr>
          </thead>
          <tbody>
          <?php foreach($categories as $category) : ?>
            <tr>
              <td><?= $category['id'] ?></td>
              <td><?= $category['category'] ?></td>
              <td>
                <a
                  class="btn btn-warning"
                  title="Modifier le produit"
                  href="admin_category_update.php?id=<?= intval( $category['id'] ); ?>">
                  <i class="fa fa-pen-nib" aria-hidden="true"></i>
                </a>
              </td>
              <td>
                <button type="button" 
                  class="btn btn-danger" 
                  data-toggle="modal" 
                  data-target="#myModal<?= $category['id'] ?>">
                  <i class="fa fa-trash" aria-hidden="true"></i>
                </button>
<!-- modal content -->
                  <div id="myModal<?= $category['id'] ?>"  class="modal" tabindex="-1">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        
                        <div class="modal-header">
                          <h5 class="modal-title">Modal title</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>

                        <div class="modal-body">
                          <p>Voulez vous supprimer le categorie N°<?= $category['id'] ?></p>
                        </div>

                        <div class="modal-footer">
                          <a class="btn btn-danger btn-lg "
                            data-indice="<?= intval( $category['id'] ); ?>"
                            title="Supprimer le post"
                            href="admin_category_delete.php?id=<?= $category['id'] ?>">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                          </a>
                          <a class="btn btn-dark btn-lg"
                            data-dismiss="modal"
                            title="J'abandonne !"
                            href="admin_author_index.php">
                            <i class="fa fa-hand-paper" aria-hidden="true"></i>
                          </a>
                        </div>

                      </div>
                    </div>
                </div>
              </td>
            </tr>
            <?php endforeach ; ?>
          </tbody>
        </table>
      </div>