<div class="mr-3">
<form method="post" action="admin_category_insert.php" class="mx-5"> 
      <fieldset class="pr-2">
        <legend class="text-center display-4 pb-2  bg-secondary">Ajout d'une categorie</legend>                      
    <ul>
       <li>
         <label class="text-dark" for="">Categorie :</label>
         <input type="text"
           name="category"
           class="form-control">
       </li> 
    </ul>               
      <div class="modal-footer">
        <button name="envoyer" type="submit"  class="btn btn-info"> Add </button>
      </div>
    </fieldset>
  </form>
</div>