<?php if(!empty($products)) : ?>
  <div class="d-flex justify-content-between flex-wrap my-5 mx-0 px-0"> 
                <?php foreach($products as $product) : ?>
                <div class="row mx-3 my-2 show-product border border-secondary rounded overflow-hidden d-flex justify-content-between ">
                  <div >
                    <div class=" row g-0  mb-4 shadow-sm h-md-250 position-relative ml-0 ">
                      <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary"><?= $product['category'] ?></strong>
                        <h3 class="mb-0"><?= $product['title'] ?></h3>
                        <div class="mb-1 text-muted">
                          <time
                              datetime="<?= htmlspecialchars( $product['date_creation'] ); ?>">
                                <?= htmlspecialchars( $product['DateMaj'] ); ?>
                          </time>
                        </div>
                        
                      </div>
                      <div class="col-auto d-none d-lg-block">
                        <img class="bd-placeholder-img" width="150" height="150" src="img/<?= $product['image'] ?>" >
                      </div>
                      <p class="card-text mb-auto ml-1"><?= $product['Excerpt'] ?>[...]</p>
                      <a href="show_product.php?id=<?= intval( $product['id_product'] ); ?>"  class=" details stretched-link text-dark border rounded bg-warning text-center mt-4 px-3 py-1" style="
                    margin-left: 150px;">Détails..</a>
                  </div>
                </div>
                </div>
                <?php endforeach ;?>
            </div>
          <?php else : ?>
              
                <p class=" mt-5 text-center text-muted display-4"><?= $msg ?></p>
            
              <?php endif ?>
           
           
