<main class="container-fluid">
        <section class="d-flex justify-content-between ">

            <aside class="second-nav">
                <p>Categories    ></p>
                <ul class="navcategory">
                    <li><a href="#" class="nav-link px-2 li-category">Informatiques ></a></li>
                    <li><a href="#" class="nav-link px-2 li-category">Automobile ></a></li>
                    <li><a href="#" class="nav-link px-2 li-category">Maison & Bureau ></a></li>
                    <li><a href="#" class="nav-link px-2 li-category">Electroniques ></a></li>
                    <li><a href="#" class="nav-link px-2 li-category">Agriculture ></a></li>
                  </ul>
                  <a class="btn btn-warning mt-5 font-weigth-bold ml-5" href="registre_auth.php">Ajouter un produit</a>
                  <video width="250" height="240" controls>
                    <source src="img/MB SHOPPING FOLIES JEU DE SOCIETE PARLANT   Publicité Ina fr.mp4" type="video/mp4">
                  </video>
            </aside>

            <article class="corp">
              
                <div class=" banner"></div>
                <h2 class="text-center text-warning mt-2 pt-4 pb-2 border-top border-info ">Nouveaux Produits</h2>
                <div class="d-flex justify-content-between "> 
                <?php foreach($products as $product) : ?>
                <div class="row mx-0 my-2 show-product border border-info rounded overflow-hidden d-flex justify-content-between ">
                  <div >
                    <div class=" row g-0  mb-4 shadow-sm h-md-250 position-relative ml-0 ">
                      <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary"><?= $product['category'] ?></strong>
                        <h3 class="mb-0"><?= $product['title'] ?></h3>
                        <div class="mb-1 text-muted">
                          <time
                              datetime="<?= htmlspecialchars( $product['date_creation'] ); ?>">
                                <?= htmlspecialchars( $product['DateMaj'] ); ?>
                          </time>
                        </div>
                        
                      </div>
                      <div class="col-auto d-none d-lg-block">
                        <img class="bd-placeholder-img" width="150" height="150" src="img/<?= $product['image'] ?>" >
                      </div>
                      <p class="card-text mb-auto ml-1"><?= $product['Excerpt'] ?>[...]</p>
                      <a href="show_product.php?id=<?= intval( $product['id_product'] ); ?>"  class=" details stretched-link text-dark border rounded bg-warning text-center mb-2 px-3 py-1" style="
                    margin-left: 150px;">Détails..</a>
                  </div>
                </div>
                </div>
                <?php endforeach ;?>
            </div>
    </article>
  </section>
</main>