<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 3jeja:site web vente et achat en ligne</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/b9c1830c77.js" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="css/all.min.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header class="p-3 bg-info text-white">
        <div class="container-fluid">
          <div class="d-flex flex-wrap align-items-center justify-content-between justify-content-lg-start">
            <div class="nav1  d-flex flex-direction-row justify-content-arround">
              <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" border border-white aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
              </a>
      
              <ul class="nav me-lg-auto mb-2 d-flex justify-content-arround mb-md-0">
                <li><a href="index.php" class="nav-link px-2 text-secondary">Accueil</a></li>
                <li><a href="All_product.php" class="nav-link px-2 text-white">Produit</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Contact</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Commande</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Mon Espace</a></li>
              </ul>
            </div>
            <div class="nav2 d-flex flex-direction-row justify-content-end">
              <form class=" mb-3 mb-lg-0 me-lg-3 mr-3 ">
                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
              </form>
      
              <div class="text-end">
               <a class="btn btn-outline-light me-2" href="login.php">Login</a>
               <a class="btn btn-warning" href="registre_auth.php">Sign-up</a>
              </div>
            </div>
          </div>
        </div>
      </header>
    <?php include $template . '.phtml' ?>
    <footer class="bg-info container-fluid py-5 ">
        
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>