<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 3jeja:site web vente et achat en ligne</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/b9c1830c77.js" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="css/all.min.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header class="p-3 bg-info text-white">
        <div class="container-fluid">
          <div class="d-flex align-items-center justify-content-around justify-content-lg-start">
            <div class="nav  d-flex flex-direction-row justify-content-arround">
              <a href="index.php" class=" nav-log ">
                <img src="img/3jeja.png" alt="logo-3jeja" class="logo">
              </a>
              </div>
              <ul class="nav1 me-lg-auto mb-2 d-flex justify-content-arround mb-md-0">
                <li><a href="index.php" class="nav-link px-2 ">Accueil</a></li>
                <li><a href="All_product.php" class="nav-link px-2 ">Produits</a></li>
                <li><a href="#" class="nav-link px-2 ">Commande</a></li>
                <li><a href="login.php" class="nav-link px-2 ">Mon Espace</a></li>
              </ul>
          
            <div class="nav2 d-flex flex-direction-row justify-content-end">
              <form class=" mb-3 mb-lg-0 me-lg-3 mr-3 " action="search.php" method="post">
                <input type="search" 
                name="search"
                class="form-control form-control-dark" 
                placeholder="Search..." 
                aria-label="Search">
              </form>
              <?php if(substr($template,0,6)=='admin_') : ?>
              <div class="text-end nav-item">
                <a class="btn text-white me-2" href="#">Admin</a>
                <a class="btn btn-outline-light me-2" href="deconnect.php">Log Out</a>
              </div>
            
              
              <?php else : ?>  
                  <?php if(isset($_SESSION['logged'])) : ?>
              <div class="text-end">
               <a class="btn btn-outline-light me-2" href="deconnect.php">Log Out</a>
               <p>@<?= $_SESSION['firstname'] ?> <?= $_SESSION['lastname'] ?></p>
              </div>
                  <?php else : ?>
              <div class="text-end<?php if(substr($template,0,6) !='admin_') echo 'active' ;  ?> ">
               <a class="btn btn-outline-light me-2" href="login.php">Login</a>
               <a class="btn btn-warning" href="registre_auth.php">Sign-up</a>
              </div>
                  <?php endif ; ?>
              <?php endif ; ?>
            </div>
          </div>
        </div>
      </header>
      <main class="container-fluid">
        <section class="d-flex justify-content-between ">
            <aside class="second-nav">
                <p>Categories    ></p>
                <ul class="navcategory">
                <?php if(substr($template,0,6)=='admin_') : ?>
                    <li><a href="admin_product_index.php" class="nav-link px-2 li-category">Gestion des produits ></a></li>
                    <li><a href="admin_category_index.php" class="nav-link px-2 li-category">Gestion des categories ></a></li>
                    <li><a href="admin_author_index.php" class="nav-link px-2 li-category">Gestion des authors ></a></li>
                    <li><a href="admin_comment_index.php" class="nav-link px-2 li-category">Gestion des Commentaires ></a></li>
                <?php else : ?>
                    <li><a href="categ_infos.php" class="nav-link px-2 li-category">Informatiques ></a></li>
                    <li><a href="categ_automobile.php" class="nav-link px-2 li-category">Automobile ></a></li>
                    <li><a href="categ_deco.php" class="nav-link px-2 li-category">Maison & Bureau ></a></li>
                    <li><a href="careg_elect.php" class="nav-link px-2 li-category">Electroniques ></a></li>
                    <li><a href="categ_electrecité.php" class="nav-link px-2 li-category">Electricité ></a></li>
                <?php endif ; ?>
                  </ul>
                  <?php if(isset($_SESSION['logged'])) : ?>
                  <a class="btn btn-warning mt-5 font-weigth-bold ml-5" href="add_product.php">Ajouter un produit</a>
                  <?php endif ;?>
                  <?php if(substr($template,0,6) !='admin_') : ?>
                  <video width="250" height="240" controls>
                    <source src="img/MB SHOPPING FOLIES JEU DE SOCIETE PARLANT   Publicité Ina fr.mp4" type="video/mp4">
                  </video>
                  <?php endif ; ?>
            </aside>
            <article class="corp">
                <?php include $template . '.phtml' ?>
            </article>
        </section>
    </main>
    <footer class="bg-info container-fluid py-5 ">
        
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/panier.js"></script>
</body>
</html>