<div class="text-center" style="margin-bottom:100px;margin-top:100px">
  <form class="form-signin"  method="post">

    <img class="mb-4" src="/docs/4.6/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
    <label for="inputEmail" class="sr-only ">First Name :</label>
    <input type="text" name="FirstName" class="form-control" placeholder="First Name" required autofocus>
    <label for="inputEmail" class="sr-only ">Last Name :</label>
    <input type="text" name="LastName" class="form-control " placeholder="Last Name"  required autofocus>
    <label for="inputEmail" class="sr-only ">Email address</label>
    <input type="email" name="inputEmail" class="form-control " placeholder="Email address"  required autofocus>
    <label for="inputPassword" class="sr-only">Password :</label>
    <input type="password" name="inputPassword" class="form-control "  placeholder="Password" required>
    <label for="inputEmail" class="sr-only ">Address :</label>
    <input type="text" name="inputAddress" class="form-control " placeholder="Address"  required autofocus>
    <div class="checkbox my-2 ">
      <input type="checkbox" value="remember-me"> Remember me
    </div>
    <button class="btn btn-lg btn-primary btn-block w-50" type="submit" style="margin-left:70px;">Sign in</button>
    
  </form>
</div>